{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "xlb.fullname" . }}
  labels:
    {{- include "xlb.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["endpoints", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "xlb.fullname" . }}
  labels:
    {{- include "xlb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "xlb.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "xlb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
